### ISSUE TITLE
Create Api Specification

### ISSUE THREAD

**Issue by FilipeDominguesGit** [FilipeDominguesGit/psidi-rest-api#1]
# **Use Cases**
1. Register a user
2. Create a new data set from CSV, XML, JSON
3. Modify an existing data set
4. Return a data set as CSV, XML, JSON
5. Show the number of elements in the data set or selected row/column
6. Calculate total row
7. Calculate total column
8. Calculate statistical measures of a row, column, entire data set
   a. geometric mean
   b. median
   c. Mode
   d. Midrange
   e. Variance
   f. standard deviation
9. Perform transformations on the data set (without changing the original data set)
   a. Transpose the dataset
   b. Scale
   c. Add a scalar
   d. Add two data sets
   e. Multiply two data sets
   f. Augment the data set using linear interpolation on the rows or columns
10. Return a chart representation (image binary file) of the dataset
    a. Pie chart of a desired row/column
    b. Line/bar chart of a desired row/column
    c. Line/bar chart of the entire data set
11. Define a macro
12. Load a macro
13. Execute a macro on an existing dataset
## Bonus
1. Register new worker in pool registry
2. “Heart beat” of a worker
3. Use OAuth authentication

[PSIDI_assignment_2016-2017.pdf](https://github.com/FilipeDominguesGit/psidi-rest-api/files/555582/PSIDI_assignment_2016-2017.pdf)

**Comment by FilipeDominguesGit** [comment]
### Users ###

/Users
/Users/:id

/Users/:id/Datasets
/Users/:id/Datasets/:id/Statistics
/Users/:id/Datasets/:id/rows
/Users/:id/Datasets/:id/rows/:id/Statistics
/Users/:id/Datasets/:id/columns
/Users/:id/Datasets/:id/columns/:id/Statistics

/Users/:id/Tranformations
/Users/:id/Tranformations/:id

/Users/:id/Macros
/Users/:id/Macros/:id

### DataSets ###

/DataSets
/DataSets/:id
/Datasets/:id/rows
/Datasets/:id/rows/:id
/Datasets/:id/columns
/Datasets/:id/columns/:id

### Macros ###

/Macros
/Macros/:id

### Transformations ###

/Tranformations
/Tranformations/:id

**Comment by NunoDomingues** [comment]
-----------------------------------------------------------------------------------------------
# Users
___________________________________
### /Users


> GET - N/A (List all Users - If auth).
> POST - Create User.
> PUT - N/A
> DELETE - N/A


___________________________________
### /Users/:id


> GET - Get Info for user with the id.
> POST - N/A
> PUT - Update User info.
> DELETE - N/A


___________________________________
### /Users/:id/Datasets (Doubt - ASK PAG)


> GET - Get User DataSets
> POST - Create DataSet
> PUT - N/A
> DELETE -  N/A


___________________________________
### /Users/:id/Transformations  (Doubt - ASK PAG)


> GET - List all user transformations
> POST - Create a new transformation
> PUT -  N/A
> DELETE -  N/A


# DataSets
___________________________________
### /DataSets

> GET - Lists all user datasets
> POST - Creates new dataset
> PUT - N/A
> DELETE -  N/A

___________________________________
### /DataSets/:id


> GET - Get DataSet data
> POST - Update DataSet
> PUT - Overwrite DataSet
> DELETE -  Delete DataSet


___________________________________
### /Datasets/:id/Statistics (NEW)
Missing(Define filters)

> GET - Get Statistic from DataSet from entire set
> POST - N/A
> PUT - N/A
> DELETE - N/A
___________________________________
### /Datasets/:id/rows

> GET - N/A
> POST - Creates new row (when creating rows, adds after the end of dataset)
> PUT - N/A
> DELETE - N/A

___________________________________
### /Datasets/:id/rows/:n

> GET - Gets Row Data
> POST - Update  Row 
> PUT - Create or overwrite  Row 
> DELETE - Delete  Row 

___________________________________
### /Datasets/:id/rows/:n/sum

> GET - Gets Row Sum
> POST - N/A
> PUT - N/A
> DELETE - N/A


___________________________________
### /Datasets/:id/rows/:n/count

> GET - Gets Number of Elements of Row
> POST - N/A
> PUT - N/A
> DELETE - N/A

___________________________________
### /Datasets/:id/rows/:n/Statistics (NEW)
Missing(Define filters)

> GET - Gets statistics from entire row
> POST - N/A
> PUT - Update Row
> DELETE - Delete Row
___________________________________
### /Datasets/:id/columns

> GET -  N/A
> POST - Create column (when creating columns, adds after the end of dataset)
> PUT -  N/A
> DELETE - N/A


___________________________________
### /Datasets/:id/columns/:n

> GET - Get column
> POST - Update column
> PUT - Create or overwrite column
> DELETE - Delete column


___________________________________
### /Datasets/:id/columns/:n/sum


> GET - Gets Column Sum
> POST - N/A
> PUT - N/A
> DELETE - N/A


___________________________________
### /Datasets/:id/columns/:id/count


> GET - Gets Number of Elements of Column
> POST - N/A
> PUT - N/A
> DELETE - N/A
___________________________________


### /Datasets/:id/column/:n/Statistics (NEW)
(Missing filters)

> GET - Gets statistics from entire column
> POST - N/A
> PUT - N/A
> DELETE - N/A


# Transformations 


### /Transformations

> GET - List all user transformations
> POST - Create a new transformation
> PUT -  N/A
> DELETE -  N/A

___________________________________

### /Transformations/:id

> GET - List transformation
> POST - N/A
> PUT -  N/A
> DELETE -  Delete Transformation


# Macros #
___________________________________
### /Macros

> GET - get all
> POST - create
> PUT - N/A
> DELETE - N/A 


___________________________________
### /Macros/:id

> GET - get macro by id
> POST - update
> PUT - override
> DELETE -  delete


___________________________________
### /Macros/:id/run

> GET - N/A
> POST - exec
> PUT - N/A
> DELETE -  N/A

___________________________________
