### ISSUE TITLE
Create sequence diagram.

### ISSUE THREAD

**Issue by FilipeDominguesGit** [FilipeDominguesGit/psidi-rest-api#6]
https://www.websequencediagrams.com

https://www.draw.io

**Comment by FilipeDominguesGit** [comment]
![client-server workflow](https://cloud.githubusercontent.com/assets/11089860/20245299/2897a2fc-a996-11e6-8843-6ba731a1becb.png)

**Comment by NunoDomingues** [comment]
Updated - Workflow

![client-server workflow](https://cloud.githubusercontent.com/assets/3798924/21554992/12a0f7ec-ce0c-11e6-9f26-4fc0e4f3f7e8.png)

**Comment by NunoDomingues** [comment]
![client-server workflow](https://cloud.githubusercontent.com/assets/3798924/21555441/11eaff6a-ce10-11e6-8027-431aa375bfb4.png)
